name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          gleam-version: "0.34.1"
      - run: gleam deps download
      - run: gleam format --check src test
      - run: gleam test
      - run: ./bin/download-compiler
      - run: gleam run
